In [59]:
import numpy as np
import pandas as pd

## Feature Construction

In [60]:
df = pd.read_csv('../titanic.csv', usecols = ['Age', 'Pclass','SibSp','Parch', 'Survived'])
df.head(5)

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [61]:
df['family_size'] = df['Parch'] + df['SibSp'] + 1
df.head()

   Survived  Pclass   Age  SibSp  Parch  family_size
0         0       3  22.0      1      0            2
1         1       1  38.0      1      0            2
2         1       3  26.0      0      0            1
3         1       1  35.0      1      0            2
4         0       3  35.0      0      0            1

In [62]:
df.dropna(inplace = True)

In [63]:
df.drop(columns = ['SibSp', 'Parch'], inplace = True)
df.head()

   Survived  Pclass   Age  family_size
0         0       3  22.0            2
1         1       1  38.0            2
2         1       3  26.0            1
3         1       1  35.0            2
4         0       3  35.0            1

In [64]:
from sklearn.model_selection import train_test_split
x = df.iloc[:,1:]
y = df.iloc[:,0]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [65]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)

In [66]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.6783216783216783

In [67]:
from sklearn.model_selection import cross_val_score
np.mean(cross_val_score(LogisticRegression(), x_train, y_train, scoring='accuracy', cv = 20))

np.float64(0.6992610837438423)

In [68]:
def find_family_type(num):
    if num == 1:
        return 0  #single
    elif num <= 3:
        return 1 #small family
    else:
        return 2 #big family

In [69]:
df['family_type'] = df['family_size'].apply(find_family_type)

In [70]:
df.head()

   Survived  Pclass   Age  family_size  family_type
0         0       3  22.0            2            1
1         1       1  38.0            2            1
2         1       3  26.0            1            0
3         1       1  35.0            2            1
4         0       3  35.0            1            0

In [71]:
df.drop(columns=['family_size'], inplace = True)

In [72]:
x = df.iloc[:,1:]
y = df.iloc[:,0]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [73]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)

In [74]:
np.mean(cross_val_score(LogisticRegression(), x_train, y_train, scoring='accuracy', cv = 20))

np.float64(0.707820197044335)

## Feature Splitting

In [75]:
df = pd.read_csv('../titanic.csv')
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [83]:
df['title'] = df['Name'].str.split(',', expand=True)[1].str.split('.', expand=True)[0]
df['name'] = df['Name'].str.split(',', expand=True)[1].str.split('.', expand = True)[1]
df.drop(columns=['Name'], inplace = True)
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,title,name
0,0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,Owen Harris
1,1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,John Bradley (Florence Briggs Thayer)
2,2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,Laina
3,3,4,1,1,female,35.0,1,0,113803,53.1000,C123,S,Mrs,Jacques Heath (Lily May Peel)
4,4,5,0,3,male,35.0,0,0,373450,8.0500,NaN,S,Mr,William Henry